
docker/start:
	docker compose -f ./docker/compose.yml up -d

docker/stop:
	docker compose -f ./docker/compose.yml down

docker/build/no_cache:
	docker compose -f ./docker/compose.yml build --no-cache
